### ISSUE TITLE
Not enough cum

### ISSUE THREAD

**Issue by torosboro** [sebailfico/Cum#1]
Hi,
I've been working on your awesome project and still cannot find any solution to get more cum. Is there any chance to change datatype to your variable `int toro=atoi(argv[1]);`. It would be great to use a long int instead of a classic integer.
Two billions of cum are not enough!

Thank you,
torosboro

**Comment by sebailfico** [comment]
Dear Torosboro,
first, thank you for your interest. It's always a pleasure to see a Cum enthusiast.
Actually this is a problem that youtube programmers know quite well, and I think that, at the same time, we should develop Cum in order to be ready to an exponential Cum growth and start thinking that 

> long is better

So thanks a lot for your support, I'll change datatype.

**Comment by sebailfico** [comment]
I've just updated the code. Unfortunately I couldn't test it because of the complex dependencies requirements of the code itself.
If you could, that would be awesome. 
PLZ keep me updated
